base_url: ''
ice_servers:
- urls:
  - 'turn:coturn.communicator.neone.systems'
  auth_type: secret
  auth_secret:
    username: neone
    secret: "some-secret"
tls:
  cert: test.pem
  key: test.key
store:
  type: redis
  redis:
    host: localhost
    port: 6379
    prefix: peercalls
network:
  type: sfu
    interfaces:
      - eth0
